# Étape 1 : Utiliser l'image officielle Cypress avec Chrome
FROM cypress/included

# Définir le dossier de travail
WORKDIR /frontend

# Copier les fichiers de configuration et installer les dépendances
COPY ./frontend/package*.json ./
RUN npm ci

# Copier tout le projet frontend
COPY ./frontend .

# Spécifier les variables d'environnement
ENV RUN_ENV=docker