#version: '3.9'
services:
  node-api:
    image: ghcr.io/dymacicd/cicd-projet2/node-api:latest
    ports:
      - '3000:80'
  frontend:
    image: ghcr.io/dymacicd/cicd-projet2/frontend:latest
    ports:
      - '80:80'
  
  cypress:
    build:
      context: .
      dockerfile: Dockerfile.cypress
    working_dir: /frontend
    volumes:
      - ./frontend/cypress:/frontend/cypress
      - ./frontend/cypress.config.cjs:/frontend/cypress.config.cjs
      - ./frontend/package.json:/frontend/package.json
    environment:
      - RUN_ENV=docker
    depends_on:
      - frontend
      - node-api
    entrypoint: >
      sh -c "RUN_ENV=$RUN_ENV && npx cypress run --headless --browser chrome --config-file /frontend/cypress.config.cjs"
