#version: '3.9'

services:
  node-api:
    image: ghcr.io/anouvene/cicd-docker/node-api:latest
    pull_policy: always
    environment:
      - NODE_ENV=production   # var d'environnement de production. Le serveur se connectera à la BD de prod.
    deploy:
      replicas: 3             # 3 instances de services crées
      update_config:        
        parallelism: 1        # màj d'un seul conteneur à la fois
        delay: 10s            # délai d'attente entre les màj
      restart_policy:
        condition: on-failure # redémarrage du conteneur en casd d'échec

  frontend:
    image: ghcr.io/anouvene/cicd-dockerfrontend:latest
    pull_policy: always
    ports:
      - target: 80      # port du conteneur sur lequel le service écoute
        published: 80   # port de l'hôte sur lequel les données seront disponibles
    restart: always     # le service sera relancé en permanence