services:
  node-api:
    build:
      context: ./node-api
      dockerfile: Dockerfile
      args:
        NODE_ENV: test
    environment:
      - NODE_ENV=test

  frontend:
    image: ghcr.io/anouvene/cicd-docker/frontend:latest
    platform: linux/amd64

  cypress:
    build:
      context: .
      dockerfile: Dockerfile.cypress
    working_dir: /frontend
    volumes:
      - ./frontend/cypress:/frontend/cypress
      - ./frontend/cypress.config.cjs:/frontend/cypress.config.cjs
      - ./frontend/package.json:/frontend/package.json
    environment:
      - RUN_ENV=docker
    depends_on:
      - frontend
      - node-api
    entrypoint: >
      sh -c "npx cypress run --headless --browser electron --env RUN_ENV=docker --config-file /frontend/cypress.config.cjs"