name: CI/CD avec images Docker et Docker Compose # Nom du workflow
on:
  push:
    branches: main
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Connexion au GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}